// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../features/auth/data/model/user_obx.dart';
import '../../features/contacts/data/models/contact_obx.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 563605376438197169),
    name: 'ContactObx',
    lastPropertyId: const obx_int.IdUid(7, 525323331091758951),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8415538626314765729),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8236655826848095961),
        name: 'contactName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3706746473609637172),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1361345023219983340),
        name: 'isAppUser',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6605622438762002214),
        name: 'userId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 8306211457572838139),
        relationTarget: 'UserObx',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 525323331091758951),
        name: 'lastCheckedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6502526937234851100),
    name: 'UserObx',
    lastPropertyId: const obx_int.IdUid(11, 6074419131432428288),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4358739026537156550),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1408384272695055967),
        name: 'serverId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6622626396874816224),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7569842160468141552),
        name: 'firstName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7108519450993566909),
        name: 'lastName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4605761413037159493),
        name: 'profileImage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6466306456443848117),
        name: 'bio',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5016076145134361201),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6824737488994072746),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6312980072067807581),
        name: 'lastSeenAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6074419131432428288),
        name: 'isOnline',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 6502526937234851100),
    lastIndexId: const obx_int.IdUid(1, 8306211457572838139),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [3979462161564861016],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ContactObx: obx_int.EntityDefinition<ContactObx>(
      model: _entities[0],
      toOneRelations: (ContactObx object) => [object.user],
      toManyRelations: (ContactObx object) => {},
      getId: (ContactObx object) => object.id,
      setId: (ContactObx object, int id) {
        object.id = id;
      },
      objectToFB: (ContactObx object, fb.Builder fbb) {
        final contactNameOffset = fbb.writeString(object.contactName);
        final phoneNumberOffset = fbb.writeString(object.phoneNumber);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contactNameOffset);
        fbb.addOffset(2, phoneNumberOffset);
        fbb.addBool(3, object.isAppUser);
        fbb.addInt64(4, object.user.targetId);
        fbb.addInt64(6, object.lastCheckedAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastCheckedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contactNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isAppUserParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final lastCheckedAtParam = lastCheckedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastCheckedAtValue);
        final object = ContactObx(
          id: idParam,
          contactName: contactNameParam,
          phoneNumber: phoneNumberParam,
          isAppUser: isAppUserParam,
          lastCheckedAt: lastCheckedAtParam,
        );
        object.user.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.user.attach(store);
        return object;
      },
    ),
    UserObx: obx_int.EntityDefinition<UserObx>(
      model: _entities[1],
      toOneRelations: (UserObx object) => [],
      toManyRelations: (UserObx object) => {},
      getId: (UserObx object) => object.obxId,
      setId: (UserObx object, int id) {
        object.obxId = id;
      },
      objectToFB: (UserObx object, fb.Builder fbb) {
        final serverIdOffset = fbb.writeString(object.serverId);
        final phoneNumberOffset = fbb.writeString(object.phoneNumber);
        final firstNameOffset = fbb.writeString(object.firstName);
        final lastNameOffset = fbb.writeString(object.lastName);
        final profileImageOffset = object.profileImage == null
            ? null
            : fbb.writeString(object.profileImage!);
        final bioOffset = object.bio == null
            ? null
            : fbb.writeString(object.bio!);
        fbb.startTable(12);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, serverIdOffset);
        fbb.addOffset(2, phoneNumberOffset);
        fbb.addOffset(3, firstNameOffset);
        fbb.addOffset(4, lastNameOffset);
        fbb.addOffset(5, profileImageOffset);
        fbb.addOffset(6, bioOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(9, object.lastSeenAt?.millisecondsSinceEpoch);
        fbb.addBool(10, object.isOnline);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final lastSeenAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final serverIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final firstNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final lastNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final profileImageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final bioParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final lastSeenAtParam = lastSeenAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSeenAtValue);
        final isOnlineParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final object = UserObx(
          obxId: obxIdParam,
          serverId: serverIdParam,
          phoneNumber: phoneNumberParam,
          firstName: firstNameParam,
          lastName: lastNameParam,
          profileImage: profileImageParam,
          bio: bioParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          lastSeenAt: lastSeenAtParam,
          isOnline: isOnlineParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ContactObx] entity fields to define ObjectBox queries.
class ContactObx_ {
  /// See [ContactObx.id].
  static final id = obx.QueryIntegerProperty<ContactObx>(
    _entities[0].properties[0],
  );

  /// See [ContactObx.contactName].
  static final contactName = obx.QueryStringProperty<ContactObx>(
    _entities[0].properties[1],
  );

  /// See [ContactObx.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<ContactObx>(
    _entities[0].properties[2],
  );

  /// See [ContactObx.isAppUser].
  static final isAppUser = obx.QueryBooleanProperty<ContactObx>(
    _entities[0].properties[3],
  );

  /// See [ContactObx.user].
  static final user = obx.QueryRelationToOne<ContactObx, UserObx>(
    _entities[0].properties[4],
  );

  /// See [ContactObx.lastCheckedAt].
  static final lastCheckedAt = obx.QueryDateProperty<ContactObx>(
    _entities[0].properties[5],
  );
}

/// [UserObx] entity fields to define ObjectBox queries.
class UserObx_ {
  /// See [UserObx.obxId].
  static final obxId = obx.QueryIntegerProperty<UserObx>(
    _entities[1].properties[0],
  );

  /// See [UserObx.serverId].
  static final serverId = obx.QueryStringProperty<UserObx>(
    _entities[1].properties[1],
  );

  /// See [UserObx.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<UserObx>(
    _entities[1].properties[2],
  );

  /// See [UserObx.firstName].
  static final firstName = obx.QueryStringProperty<UserObx>(
    _entities[1].properties[3],
  );

  /// See [UserObx.lastName].
  static final lastName = obx.QueryStringProperty<UserObx>(
    _entities[1].properties[4],
  );

  /// See [UserObx.profileImage].
  static final profileImage = obx.QueryStringProperty<UserObx>(
    _entities[1].properties[5],
  );

  /// See [UserObx.bio].
  static final bio = obx.QueryStringProperty<UserObx>(
    _entities[1].properties[6],
  );

  /// See [UserObx.createdAt].
  static final createdAt = obx.QueryDateProperty<UserObx>(
    _entities[1].properties[7],
  );

  /// See [UserObx.updatedAt].
  static final updatedAt = obx.QueryDateProperty<UserObx>(
    _entities[1].properties[8],
  );

  /// See [UserObx.lastSeenAt].
  static final lastSeenAt = obx.QueryDateProperty<UserObx>(
    _entities[1].properties[9],
  );

  /// See [UserObx.isOnline].
  static final isOnline = obx.QueryBooleanProperty<UserObx>(
    _entities[1].properties[10],
  );
}
